
###
GET  http://localhost:3100/api/v1/users/allUsers HTTP/1.1

###
POST  http://localhost:3100/api/v1/users/create HTTP/1.1
Content-Type: application/json

{
    "firstname":"new test2",
    "lastname":"new test2",
    "email":"newtest2@test.com",
    "phone":"3134902140",
    "password":"user123"
}

###
GET http://localhost:3100/api/v1/suscritos/ HTTP/1.1

###
POST  http://localhost:3100/api/v1/suscritos/new-suscribe HTTP/1.1
Content-Type: application/json

{
    "name":"pepe",
    "email":"test123@gmail.com",
    "phone":"3134902140"
}

//auth

###
Post http://localhost:3100/api/v1/auth/signin HTTP/1.1 
Content-Type: application/json

{
    "firstname":"Andres",
    "lastname": "Perez",
    "email":"andresap2017@gmail.com",
    "phone": "3134902140",
    "password":"andres123"
}


###
POST  http://localhost:3100/api/v1/suscritos/new-suscribe HTTP/1.1
Content-Type: application/json

{
    "name":"Julian",
    "email":"newtest7@test.com",
    "phone":"3207243178"
}

###
PATCH   http://localhost:3100/api/v1/suscritos/edit/65484bffcb793d56691f6774 HTTP/1.1
Content-Type: application/json

{
    "name":"Andres"
}

###
POST  http://localhost:3100/api/v1/products/new-product HTTP/1.1
Content-Type: application/json

{
    "nombre":"new test",
    "descripcion":"new test",
    "precio":2000,
    "descuento":0.03,
    "imagen":"123"
}

###
PATCH  http://localhost:3100/api/v1/products/6548495a3989f646c3b070df HTTP/1.1
Content-Type: application/json

{
    "nombre":"Aston Martin DBX707",
    "descripcion":"Eroga 707 CV de potencia y 900 Nm de bestial torque, regulado por una caja automática de nueve velocidades con convertidor de par. Su tracción es permanente a las 4 ruedas. Acelera de 0 a 100 km/h en 3,3 segundos y logra una velocidad tope de 310 km/h.",
    "precio":6000,
    "descuento":0.50,
    "imagen":"/"
}



###
PATCH http://localhost:3100/api/v1/users/changeActive/65480d21d0ca17d4de1124e7 HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:3100/api/v1/users/UserbyId/65480d21d0ca17d4de1124e7 HTTP/1.1


###
PATCH   http://localhost:3100/api/v1/users/editUser/65480d21d0ca17d4de1124e7 HTTP/1.1
Content-Type: application/json

{
    "firstname":"new test update",
    "lastname":"new test update"
}

###
GET  http://localhost:3100/api/v1/users/sendMessage HTTP/1.1


###
GET http://localhost:3100/api/v1/products HTTP/1.1


###
Post http://localhost:3100/api/v1/auth/login HTTP/1.1 
Content-Type: application/json

{
    "email":"test123@test.com",
    "current_password":"user121233"
}


###
GET http://localhost:3100/api/v1/auth/6536cdf52969ba0a03f5366f HTTP/1.1


//Eliminar usuarios (test)
###
DELETE http://localhost:3100/api/v1/users/id HTTP/1.1