
###
GET  http://localhost:3100/api/v1/users/allUsers HTTP/1.1

###
POST  http://localhost:3100/api/v1/users/create HTTP/1.1
Content-Type: application/json

{
    "firstname":"new test2",
    "lastname":"new test2",
    "email":"newtest2@test.com",
    "phone":"3134902140",
    "password":"user123"
}

###
GET http://localhost:3100/api/v1/suscritos/ HTTP/1.1

###
POST  http://localhost:3100/api/v1/suscritos/new-suscribe HTTP/1.1
Content-Type: application/json

{
    "name":"Salome",
    "email":"salome@test.com",
    "phone":"3053336288"
}


###
POST  http://localhost:3100/api/v1/suscritos/new-suscribe HTTP/1.1
Content-Type: application/json

{
    "name":"Julian",
    "email":"newtest7@test.com",
    "phone":"3207243178"
}

###
PATCH   http://localhost:3100/api/v1/suscritos/edit/65484bffcb793d56691f6774 HTTP/1.1
Content-Type: application/json

{
    "name":"Andres"
}

###
POST  http://localhost:3100/api/v1/products/new-product HTTP/1.1
Content-Type: application/json

{
    "nombre":"new test",
    "descripcion":"new test",
    "precio":2000,
    "descuento":0.03,
    "imagen":"123"
}

###
PATCH  http://localhost:3100/api/v1/products/6548494f3989f646c3b070dd HTTP/1.1
Content-Type: application/json

{
    "nombre":"Renault Twingo",
    "descripcion":"Renault",
    "precio":6000,
    "descuento":0.50,
    "imagen":"123"
}



###
PATCH http://localhost:3100/api/v1/users/changeActive/65480d21d0ca17d4de1124e7 HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:3100/api/v1/users/UserbyId/65480d21d0ca17d4de1124e7 HTTP/1.1


###
PATCH   http://localhost:3100/api/v1/users/editUser/65480d21d0ca17d4de1124e7 HTTP/1.1
Content-Type: application/json

{
    "firstname":"new test update",
    "lastname":"new test update"
}

###
GET  http://localhost:3100/api/v1/users/sendMessage HTTP/1.1


###
GET http://localhost:3100/api/v1/products HTTP/1.1